# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailhide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text="Adresse non modifié d'origine", max_length=500, unique=True, verbose_name='Adresse réelle')),
                ('key', models.CharField(help_text='Partie "k" de l\'URL générée', max_length=100, verbose_name='Clé (partie k)')),
                ('check', models.CharField(help_text='Partie "c" de l\'URL générée', max_length=100, verbose_name='Clé (partie c)')),
            ],
            options={
                'ordering': ['address'],
                'verbose_name_plural': 'Adresses mailhide',
                'verbose_name': 'Adresse mailhide',
            },
        ),
    ]
