# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailhide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailhide',
            name='check',
        ),
        migrations.AlterField(
            model_name='mailhide',
            name='key',
            field=models.CharField(help_text='Clé correspondante au mail', max_length=100, unique=True, verbose_name='Clé'),
        ),
    ]
