# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailhide', '0002_auto_20170718_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailhide',
            name='key',
            field=models.CharField(help_text='Clé correspondante au mail', max_length=10, unique=True, verbose_name='Clé'),
        ),
    ]
